import Head from "next/head";
import { useState } from "react";
import Image from "next/image";
import { Inter } from "next/font/google";
import logo from "@/assets/images/logo.webp";
import logoWhite from "@/assets/images/logo-white.webp"
import handImg from "@/assets/images/home_page_show_mob.webp";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [tab, setTab] = useState<number>(0);

  const forCustomers = (
    <div className="row w-100 red-gradient m-0 extra-rounded">
      <div className="col-6 px-5">
        <div className="p-5">
          <div className="my-3">
            <div className="display-4 fw-bold text-white">Meet</div>
            <div className="display-2 fw-bold text-white">Radius</div>
          </div>
          <div className="h5 text-white fw-bold" style={{ lineHeight: "2rem" }}>Your squad&apos;s gaming<br /> companion, reimagined.</div>
        </div>
        <Image src={handImg} alt="Radius App" className="mx-5" style={{ width: "70%", height: "auto" }} />
      </div>
      <div className="col-6 p-5">
        <div className="bg-light row w-100 extra-rounded my-3">
          <div className="col-4"></div>
          <div className="col-8 p-3">
            <div className="fw-bold">Create beacons</div>
            <div>Create beacons on your location when you play, show the city - you are playing</div>
          </div>
        </div>
        <div className="bg-light row w-100 extra-rounded my-3">
          <div className="col-4"></div>
          <div className="col-8 p-3">
            <div className="fw-bold">Show-off your skill level</div>
            <div>Whether you are a beginner, a pro turned casual or a competitive gamer - the right people will find you</div>
          </div>
        </div>
        <div className="bg-light row w-100 extra-rounded my-3">
          <div className="col-4"></div>
          <div className="col-8 p-3">
            <div className="fw-bold">Supercharge the gaming revolution</div>
            <div>Rent out your consoles, games  and gear through a trusted middle-man system. You get paid while allowing someone to jump into the rabbit hole.</div>
          </div>
        </div>
        <div className="bg-light row w-100 extra-rounded my-3">
          <div className="col-4"></div>
          <div className="col-8 p-3">
            <div className="fw-bold">Build the local community</div>
            <div>We have hid behind Reddit and Discord usernames for long enough. Bring out the real you, be bold.</div>
          </div>
        </div>
        <div className="bg-light row w-100 extra-rounded my-3">
          <div className="col-4"></div>
          <div className="col-8 p-3">
            <div className="fw-bold">Engage with your favourite publishers</div>
            <div>Nab free game licenses, exclusive items, virtual currency, subscriptions, discounts and more.</div>
          </div>
        </div>
      </div>
    </div>
  );

  const forEnterprises = (
    <div className="row w-100 blue-gradient m-0 extra-rounded">
      <div className="col-6 px-5">
        <div className="p-5">
          <div className="my-3">
            <div className="display-4 fw-bold text-white">Meet</div>
            <div className="display-2 fw-bold text-white">VidQuest</div>
          </div>
          <div className="h5 text-white fw-bold" style={{ lineHeight: "2rem" }}>Enhacing asynchronous<br /> interviews with AI</div>
        </div>
        <Image src={handImg} alt="Radius App" className="mx-5" style={{ width: "70%", height: "auto" }} />
      </div>
      <div className="col-6 p-5">
        <div className="bg-light row w-100 extra-rounded my-3">
          <div className="col-4"></div>
          <div className="col-8 p-3">
            <div className="fw-bold">Maximize your applicant pool&apos;s value</div>
            <div>Why leave potential gains on the table? Give every candidate a chance and make the best of your reputation</div>
          </div>
        </div>
        <div className="bg-light row w-100 extra-rounded my-3">
          <div className="col-4"></div>
          <div className="col-8 p-3">
            <div className="fw-bold">Break away from 1:1 deals</div>
            <div>1 minute of your people team&apos;s time : 1 minute of an interviewers time is not scaleable. Think efficient!</div>
          </div>
        </div>
        <div className="bg-light row w-100 extra-rounded my-3">
          <div className="col-4"></div>
          <div className="col-8 p-3">
            <div className="fw-bold">AI-enhanced Questions</div>
            <div>Get question ideas generated by AI from the candidate&apos;s resume like a gap or a career pivot or pen down your own</div>
          </div>
        </div>
        <div className="bg-light row w-100 extra-rounded my-3">
          <div className="col-4"></div>
          <div className="col-8 p-3">
            <div className="fw-bold">Time-stamps and Highlights</div>
            <div>We have hid behind Reddit and Discord usernames for long enough. Bring out the real you, be bold.Get a transcript of the candidate&apos;s interview along with AI curated highlights with their timestamps.</div>
          </div>
        </div>
        <div className="bg-light row w-100 extra-rounded my-3">
          <div className="col-4"></div>
          <div className="col-8 p-3">
            <div className="fw-bold">Stay reassured with product excellence</div>
            <div>We take product seriously, the user experience is designed to welcome candidates and eliminate dropoff</div>
          </div>
        </div>
      </div>
    </div>
  );

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container">
          <nav className="navbar navbar-expand-lg navbar-light justify-content-between align-items-center my-2">
            <a className="navbar-brand" href="">
              <img
                src={logo.src}
                width="auto"
                height="30"
                alt="Optigon Ventures"
              />
            </a>
            <div className="d-flex align-items-center">
              <div className="mx-3 fw-bold btn border-0" onClick={() => setTab(0)}>For Consumers</div>
              <div className="mx-3 fw-bold btn border-0" onClick={() => setTab(1)}>For Enterprises</div>
              <div className="button bg-dark text-white px-3 py-2 rounded ms-3 fw-bold btn ">
                Talk to us
              </div>
            </div>
          </nav>
          <div className="my-5 py-5">
            <div className="display-5 text-center fw-bold">
              Hello <span style={{ fontFamily: "Emoji !important" }}>👋</span>
            </div>
            <h1 className="display-1 fw-bold text-center my-4">
              We are
              <img
                src={logo.src}
                className="ms-4"
                height="100%"
                width="auto"
                alt="Optigon Ventures"
              />
            </h1>
            <div className="my-5">
              <p className="text-center mb-0 text-dark">
                We are currently running some product experiments on the market.
              </p>
              <p className="text-center mb-0 text-dark">
                Which one piques your interest?
              </p>
            </div>
            <div className="d-flex justify-content-center">
              <div
                style={{ backgroundColor: "#6A6A6A" }}
                className="d-flex rounded"
              >
                <div
                  className={`m-1 p-4 border border-dark rounded btn fw-bold ${
                    tab === 0 ? "red-gradient text-white" : "bg-light"
                  }`}
                  onClick={() => setTab(0)}
                >
                  For Consumers
                </div>
                <div
                  className={`m-1 p-4 border border-dark rounded ms-0 btn ${
                    tab === 1 ? "blue-gradient text-white" : "bg-light"
                  }`}
                  onClick={() => setTab(1)}
                >
                  For Enterprises
                </div>
              </div>
            </div>
          </div>
        </div>
        <div>{tab === 0 ? forCustomers : forEnterprises}</div>
        <footer className="bg-black mt-5 py-5 text-light">
          <div className="container d-flex justify-content-between align-items-center">
            <div>
              <Image src={logoWhite} alt="Optigon Ventures" height={50} />
              <div className="mt-4">
                <div>Optigon Ventures Private Limited,</div>
                <div>32 (1072), Munusamy Salai,</div>
                <div>West K K Nagar,</div>
                <div>Chennai - 600078</div>
              </div>
            </div>
            <div className="text-end">
              <div className="fw-bold mb-3">Quick Links</div>
              <div className="my-2">Terms and Conditions</div>
              <div className="my-2">Privacy Policy</div>
              <div className="my-2">Contact Us</div>
            </div>
          </div>
        </footer>
      </main>
    </>
  );
}
