name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn

      - name: Set environment variables
        run: |
          touch .env
          echo "STRAPI_API_URI=${{ secrets.STRAPI_API_URI }}" >> .env
          echo "STRAPI_API_KEY=${{ secrets.STRAPI_API_KEY }}" >> .env

      - name: Build Next.js app
        run: yarn build

      - name: Save build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: out

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: out

      - name: Clone repo from optigon-website
        run: |
          git clone https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_TOKEN }}@github.com/Optigon-Ventures/optigon-website

      - name: Remove all files from deploy branch
        run: |
          cd optigon-website
          git rm -r .
          git clean -fxd
          git commit -m "Remove all files"

      - name: Copy files to deploy branch
        run: |
          cd ..
          cp -r out/* optigon-website/
          cd optigon-website
          git add *
          git commit -m "Deploy build artifacts"
