name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build app
        run: yarn build

      - name: Checkout deploy branch
        uses: actions/checkout@v2
        with:
          ref: deploy
          fetch-depth: 0

      - name: Copy files to deploy branch
        run: cp -R out/* .

      - name: Commit and push changes
        run: |
          git config --global user.email "noufal@optigon.in"
          git config --global user.name "iamnoufal"
          git add .
          git commit -m "Deploy app"
          git push
